### ISSUE TITLE
Organization URL 404s

### ISSUE THREAD

**Issue by anselmbradford** [iPlantCollaborativeOpenSource/atmosphere#55]
Not sure which repo to put this in but the URL for the iPlant Collaborative GitHub Organization at https://github.com/iPlantCollaborativeOpenSource goes to http://www.iplantcollaborative.org/opensource, which doesn't exist.

**Comment by lenards** [comment]
Thanks for noting this @anselmbradford

**Comment by lenards** [comment]
the correct URL is: http://www.iplantcollaborative.org/open-source

**Comment by lenards** [comment]
looking at getting that updated - thanks again

**Comment by lenards** [comment]
@anselmbradford - I just wanted to (very tardy in doing so) note that we've updated the Organization URL to http://www.iplantcollaborative.org/open-source 

<img width="714" alt="atmo-gh-issue-1" src="https://cloud.githubusercontent.com/assets/5923/16393449/bd9475d6-3c65-11e6-8f65-6a7beb37b269.png">

**Comment by anselmbradford** [comment]
Cool, thanks!

**Comment by lenards** [comment]
Thank you for letting us know about it.
