### ISSUE TITLE
issue installing pygraphviz

### ISSUE THREAD

**Issue by usamacheema** [iPlantCollaborativeOpenSource/atmosphere#91]
When I am trying to download pygraphviz then following error occurs.

ammar@ammar-HP-15-Notebook-PC:~/Plants$ pip install pygraphviz
Collecting pygraphviz
  Using cached pygraphviz-1.3.1.tar.gz
Building wheels for collected packages: pygraphviz
 Running setup.py bdist_wheel for pygraphviz ... error
  Complete output from command /home/ammar/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ryh18C/pygraphviz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpK4uCKupip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-i686-2.7
  creating build/lib.linux-i686-2.7/pygraphviz
  copying pygraphviz/agraph.py -> build/lib.linux-i686-2.7/pygraphviz
  copying pygraphviz/version.py -> build/lib.linux-i686-2.7/pygraphviz
  copying pygraphviz/__init__.py -> build/lib.linux-i686-2.7/pygraphviz
  copying pygraphviz/graphviz.py -> build/lib.linux-i686-2.7/pygraphviz
  copying pygraphviz/release.py -> build/lib.linux-i686-2.7/pygraphviz
  creating build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_readwrite.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_attributes.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_html.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_edge_attributes.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_drawing.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_string.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_node_attributes.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_graph.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_unicode.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/__init__.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_clear.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_attribute_defaults.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_subgraph.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  copying pygraphviz/tests/test_layout.py -> build/lib.linux-i686-2.7/pygraphviz/tests
  running egg_info
  writing pygraphviz.egg-info/PKG-INFO
  writing top-level names to pygraphviz.egg-info/top_level.txt
  writing dependency_links to pygraphviz.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'pygraphviz.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '.svn' found anywhere in distribution
  no previously-included directories found matching 'doc/build'
  writing manifest file 'pygraphviz.egg-info/SOURCES.txt'
  copying pygraphviz/graphviz.i -> build/lib.linux-i686-2.7/pygraphviz
  copying pygraphviz/graphviz_wrap.c -> build/lib.linux-i686-2.7/pygraphviz
  running build_ext
  building 'pygraphviz._graphviz' extension
  creating build/temp.linux-i686-2.7
  creating build/temp.linux-i686-2.7/pygraphviz
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ammar/anaconda2/include/python2.7 -c pygraphviz/graphviz_wrap.c -o build/temp.linux-i686-2.7/pygraphviz/graphviz_wrap.o
  pygraphviz/graphviz_wrap.c:2954:29: fatal error: graphviz/cgraph.h: No such file or directory
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pygraphviz
  Running setup.py clean for pygraphviz
Failed to build pygraphviz
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz ... error
    Complete output from command /home/ammar/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ryh18C/pygraphviz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Rh8hBS-record/install-record.txt --single-version-externally-managed --compile:
    running install
    Trying pkg-config
    Package libcgraph was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libcgraph.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libcgraph' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Ryh18C/pygraphviz/setup.py", line 87, in <module>
        tests_require=['nose>=0.10.1', 'doctest-ignore-unicode>=0.1.0',],
      File "/home/ammar/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/ammar/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/ammar/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-Ryh18C/pygraphviz/setup_commands.py", line 44, in modified_run
        self.include_path, self.library_path = get_graphviz_dirs()
      File "/tmp/pip-build-Ryh18C/pygraphviz/setup_extra.py", line 121, in get_graphviz_dirs
        include_dirs, library_dirs = _pkg_config()
      File "/tmp/pip-build-Ryh18C/pygraphviz/setup_extra.py", line 44, in _pkg_config
        output = S.check_output(['pkg-config', '--libs-only-L', 'libcgraph'])
      File "/home/ammar/anaconda2/lib/python2.7/subprocess.py", line 573, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['pkg-config', '--libs-only-L', 'libcgraph']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/home/ammar/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ryh18C/pygraphviz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Rh8hBS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Ryh18C/p

**Comment by steve-gregory** [comment]
Perhaps this should be brought up here: https://github.com/pygraphviz/pygraphviz/issues

**Comment by arleigh16** [comment]
Is there any way at all to get my email list off of your mailing list?  Are there administrators who can remove an email address?
 Arleigh Birchler "Wild Azalea Home" ** Sent from my Intergalactic Star Cruiser **

**Comment by steve-gregory** [comment]
@arleigh16 this is *not* a mailing list. You are receiving this
notification because you are either:
1. Starred the project Atmosphere
or
2. Watching the project Atmosphere

Because this is not a mailing list we are not able to remove you. You can
remove yourself by going here:
https://github.com/iPlantCollaborativeOpenSource/atmosphere
Then selecting 'Unstar' or 'Unwatch' as is appropriate for your situation.

Thanks,

Steve Gregory
Technical Lead of Atmosphere

**Comment by usamacheema** [comment]
Hi mr steve

**Comment by usamacheema** [comment]
Mr steve could you tell me if I could contribute iplant  project as i am new on github
